algoritmo "semnome"
// Função :
// Autor :
// Data : 16/02/2022
// Seção de Declarações 
var
B: REAL
H: REAL
AR: REAL
TIN: REAL
inicio
ESCREVA ("DIMENSÃO DA BASE DA PAREDE EM METROS: ")
Leia (B)
Escreva ("ALTURA DA PAREDE EM METROS: ")
LEIA(H)
AR <-(B*H)
TIN <-(AR/2)
Escreva ("A área da parede é de ",AR,"m², e serão necessarios ",TIN," litros de tinta para pintá la")
fimalgoritmo
